apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-spring-pv
  namespace: fleet-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/postgres2
